# Generated by Django 4.2.8 on 2023-12-15 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('investment_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('interest_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('cashflow_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cashflow_date', models.DateField()),
                ('cashflow_currency', models.CharField(max_length=5)),
                ('cashflow_type', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loan')),
            ],
        ),
    ]
